version: "3.6"
services:
  app:
    build: "."
    container_name: nodeTurtle
    image: node_turtle:latest
    environment: 
      - PORT:3000
    ports:
      - "3000:3000"
    #  - "9229:9229"
    volumes: 
      - "."
    restart: unless-stopped